### ISSUE TITLE
Layout Collision on Navbar and Text Element

### ISSUE THREAD

**Issue by suryamsj** [finic-ai/finic#84]
Hello, I noticed an issue on the website where the navigation bar elements overlap with the main header text on the home page (screenshot attached). This issue seems to affect readability and overall user experience.

**Steps to Reproduce:**
1. Open the homepage (URL: [finic.io](https://finic.io)).
2. Observe the overlap between the navbar and the main content section.

**Expected Behavior:**  
The navbar and header text should not overlap and should maintain a clean separation for a better visual structure.

**Actual Behavior:**  
The navbar appears to collide with the header text across all screen sizes.

**Screenshot:**  
![screenshot](https://github.com/user-attachments/assets/8f4b95b1-3714-476c-8f98-e08e8d5d337b)

**Potential Fix:**  
I would like to contribute by fixing this issue. It might involve adjusting the CSS for responsive layout or adding spacing to prevent the overlap.

**Question:**  
Is this something I can contribute to? If so, I would be happy to open a pull request to resolve the problem. Please let me know if there are any guidelines I should follow when contributing.

Thank you!

**Comment by jasonwcfan** [comment]
Thanks for catching that @suryamsj! Unfortunately we use Framer to host our website so it's not open source, but feel free to open a PR for other issues related to the SDK. We'll be cleaning the repo up and adding bounties at some point in the future.

**Comment by suryamsj** [comment]
> Thanks for catching that @suryamsj! Unfortunately we use Framer to host our website so it's not open source, but feel free to open a PR for other issues related to the SDK. We'll be cleaning the repo up and adding bounties at some point in the future.

Thank you for the quick response! I understand that the website is hosted on Framer and not open source. I'll keep an eye out for SDK-related issues and would be happy to contribute.
